name: APK to EXE Converter Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Python and Dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Required Packages
      run: |
        pip install flask pyinstaller
        sudo apt-get update
        sudo apt-get install -y scrcpy

    - name: Run the Flask App
      run: |
        nohup python app.py &
        sleep 10  # Ensure the app has started before any frontend requests

    - name: Convert APK to EXE
      run: |
        # Use a sample APK file for testing
        curl -O https://example.com/sample.apk
        curl -X POST -F "file=@sample.apk" http://127.0.0.1:5000/upload --output converted.exe

    - name: Upload Converted File
      uses: actions/upload-artifact@v3
      with:
        name: converted-exe
        path: converted.exe
